services:
  - type: web
    name: skv-flask-uploader
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_yliZ19YbeQhV@ep-mute-cloud-a1ecwvbi-pooler.ap-southeast-1.aws.neon.tech/skv-employees?sslmode=require&channel_binding=require
